[package]
name = "tracerr"
version = "0.1.2"
edition = "2018"
description = "Custom compile time captured error tracing"
authors = ["Instrumentisto Team <developer@instrumentisto.com>"]
license = "BlueOak-1.0.0"
documentation = "https://docs.rs/tracerr"
homepage = "https://github.com/instrumentisto/tracerr-rs"
repository = "https://github.com/instrumentisto/tracerr-rs"
readme = "README.md"
keywords = ["backtrace", "error", "stacktrace", "tracing", "tracerr"]
categories = []
include = ["/src/", "/Cargo.toml", "/CHANGELOG.md", "/LICENSE.md", "/README.md"]

[package.metadata.docs.rs]
features = ["failure"]

[dependencies]
derive_more = "0.99.2"
[dependencies.failure]
    version = "0.1.6"
    optional = true
    default-features = false
    features = ["backtrace"]
