name: Security audit

on:
  push:
    tags-ignore: ["v*"]
    paths: ["Cargo.toml"]
  pull_request:
    paths: ["Cargo.toml"]
  schedule:
    - cron: "7 7 * * *"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
